catalog/urls.py
from django.conf.urls import url
from .views import OrganizationView, OrganizationsView

urlpatterns = [
    url(r'^organizations/(?P<slug>[\w-]+)$', OrganizationView.as_view(), name='organization'),
    url(r'^organizations/$', OrganizationsView.as_view(), name='organizations'),
]

cms/urls.py
from django.conf.urls import url
from .views import HomeView, ArticleView, ArticlesView

urlpatterns = [
    url(r'^articles/$', ArticlesView.as_view(), name='articles'),
    url(r'^$', HomeView.as_view(), name='home'),
]

vannevar/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import User

from catalog import urls as catalog_urls
from cms import urls as cms_urls

urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),
    url(r'^', include(catalog_urls, namespace='catalog')),
    url(r'^', include(cms_urls, namespace='cms')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.views.generic import TemplateView

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vannevar/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Vannevar</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <script src="{% static 'vannevar/js/vendors.min.js' %}"></script>
</head>
<body>
    {% include 'header.html' %}
    {% block 'main' %}
        <main id="main_content">
            <h3>Base Template</h3>
            <p>This is default Base template text.</p>
        </main>
    {% endblock 'main' %}
    {% include 'footer.html' %}

</body>
</html>

vannevar/templates/footer.html
{% block 'footer' %}
<footer>
    <p><small>© 2016 Berry Catalog Workshop.  All rights reserved.</small></p>
</footer>
{% endblock 'footer' %}

vannevar/templates/header.html
{% block 'header' %}
<header>
    <h2>Vannevar.org</h2>

    <ul>
        <li><a href="{% url 'cms:home' %}">Home</a></li>
        <li><a href="{% url 'cms:articles' %}">Articles</a></li>
        <li><a href="{% url 'catalog:organizations' %}">Organizations</a></li>
    </ul>
</header>
{% endblock 'header' %}